const MASTER_QUOTER_V2_TYPES = ['TEMPLATE', 'TOUR_OPTION'];
const MASTER_QUOTER_V2_ITEM_PLACEMENTS = ['services', 'options'];
const MASTER_QUOTER_V2_STATUSES = ['ACTIVE', 'INACTIVE', 'DRAFT'];

module.exports = {
  MASTER_QUOTER_V2_TYPES,
  MASTER_QUOTER_V2_ITEM_PLACEMENTS,
  MASTER_QUOTER_V2_STATUSES,
};
